### ISSUE TITLE
Missing library in java image when awt is used

### ISSUE THREAD

**Issue by focdanisch** [paketo-buildpacks/bellsoft-liberica#192]
## What happened?
Hello,

I hope that this is the right place to discuss this topic. Our application uses Spring Boot 2.5.6. Maven builds our application as Spring Boot enabled jar file without problems for quite some time. Now, for initial testing of docker container creation, I used

```
mvn spring-boot:build-image
```

to try to automatically create a docker image. This worked right out of the box, so I started a container from this image. Our application first starts as it should, but then we are confronted with a stacktrace:

```
2021-12-07 10:40:33,956 ERROR [            main                   ] o.a.c.c.C.[Tomcat].[localhost].[/]       : Exception starting filter [javamelody]
java.lang.UnsatisfiedLinkError: /layers/paketo-buildpacks_bellsoft-liberica/jdk/lib/libawt_xawt.so: libXtst.so.6: cannot open shared object file: No such file or directory
        at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
        at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2442)
        at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2498)
        at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2694)
        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2627)
        at java.base/java.lang.Runtime.load0(Runtime.java:768)
        at java.base/java.lang.System.load(System.java:1837)
        at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
        at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2442)
        at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2498)
        at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2694)
        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2648)
        at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:830)
        at java.base/java.lang.System.loadLibrary(System.java:1873)
        at java.desktop/java.awt.Toolkit$3.run(Toolkit.java:1395)
        at java.desktop/java.awt.Toolkit$3.run(Toolkit.java:1393)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.desktop/java.awt.Toolkit.loadLibraries(Toolkit.java:1392)
        at java.desktop/java.awt.Toolkit.<clinit>(Toolkit.java:1425)
        at java.desktop/java.awt.Color.<clinit>(Color.java:275)
        at net.bull.javamelody.internal.model.JRobin.<clinit>(JRobin.java:71)
        at net.bull.javamelody.FilterContext.initCollect(FilterContext.java:271)
        at net.bull.javamelody.FilterContext.<init>(FilterContext.java:137)
        at net.bull.javamelody.MonitoringFilter.init(MonitoringFilter.java:148)
        at org.apache.catalina.core.ApplicationFilterConfig.initFilter(ApplicationFilterConfig.java:270)
        at org.apache.catalina.core.ApplicationFilterConfig.<init>(ApplicationFilterConfig.java:105)
        at org.apache.catalina.core.StandardContext.filterStart(StandardContext.java:4613)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5256)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1396)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1386)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
        at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:140)
        at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:919)
        at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:835)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1396)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1386)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
        at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:140)
        at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:919)
        at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:263)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
        at org.apache.catalina.core.StandardService.startInternal(StandardService.java:432)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
        at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:927)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
        at org.apache.catalina.startup.Tomcat.start(Tomcat.java:486)
        at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.initialize(TomcatWebServer.java:123)
        at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.<init>(TomcatWebServer.java:104)
        at org.springframework.boot.web.embedded.tomcat.TomcatServletWebServerFactory.getTomcatWebServer(TomcatServletWebServerFactory.java:450)
        at org.springframework.boot.web.embedded.tomcat.TomcatServletWebServerFactory.getWebServer(TomcatServletWebServerFactory.java:199)
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.createWebServer(ServletWebServerApplicationContext.java:182)
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:160)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:577)
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:145)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:754)
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:434)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:338)
        at de.foconis.core.app.SysUtils.run(SysUtils.java:289)
        at de.foconis.core.app.SysUtils.run(SysUtils.java:109)
        at de.foconis.zak.runner.ApplicationInitializer.main(ApplicationInitializer.java:58)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
        at org.springframework.boot.loader.WarLauncher.main(WarLauncher.java:59)
```

JavaMelody is integrated into our application and it is initialized during bootup. When I look into JRobin.java:71, I see:

```
private static final Color PERCENTILE_COLOR = new Color(200, 50, 50);`
```

Judging from the imports, this class needs a few other awt classes as well:

```
import java.awt.Color;
import java.awt.Font;
import java.awt.GradientPaint;
import java.awt.Paint;
```

So when intializing this class, it tries to load the libawt_xawt.so library, which in turn tries to load libXtst.so.6, which is not present in the image. I also tested it with the full image, but I get the same error.

It seems to me, that there is a library missing in the base image that Java needs to function properly. Can this be integrated into one of the images?

## Build Configuration

We use spring-boot-2.5.6 as basic framework. These are the configuration changes of the spring-boot-maven-plugin (I tested it with base and full, therefore the comment, I tested it without the whole image-Block as well):

```
<image>
	<!--<builder>paketobuildpacks/builder:full</builder>-->
	<env>
		<BP_JVM_TYPE>JDK</BP_JVM_TYPE>
		<BP_JVM_VERSION>11.*</BP_JVM_VERSION>
		<BPL_DEBUG_ENABLED>true</BPL_DEBUG_ENABLED>
		<BPL_HEAP_DUMP_PATH>/tmp/heapdump.hprof</BPL_HEAP_DUMP_PATH>
	</env>
</image>
```

I see this output when running spring-boot:build-image:

```
[INFO]  > Pulling builder image 'docker.io/paketobuildpacks/builder:base' 100%
[INFO]  > Pulled builder image 'paketobuildpacks/builder@sha256:5f5b269e93b0519f993562b0560ba73fbf24f50d3fe4a5f62ba40cb323571fa0'
[INFO]  > Pulling run image 'docker.io/paketobuildpacks/run:base-cnb' 100%
[INFO]  > Pulled run image 'paketobuildpacks/run@sha256:b1e8add4fc569e37085342cd05186d17cb81e128ee60fd9fd633337e25ac7808'
[INFO]  > Executing lifecycle version v0.13.1
[INFO]  > Using build cache volume 'pack-cache-bc545c05cd44.build'
[INFO]
[INFO]  > Running creator
[INFO] Layout: WAR
[INFO]     [creator]     ===> DETECTING
[INFO]     [creator]     6 of 19 buildpacks participating
[INFO]     [creator]     paketo-buildpacks/ca-certificates   3.0.1
[INFO]     [creator]     paketo-buildpacks/bellsoft-liberica 9.0.1
[INFO]     [creator]     paketo-buildpacks/syft              1.0.1
[INFO]     [creator]     paketo-buildpacks/executable-jar    6.0.1
[INFO]     [creator]     paketo-buildpacks/dist-zip          5.0.1
[INFO]     [creator]     paketo-buildpacks/spring-boot       5.1.0
[INFO]     [creator]     ===> ANALYZING
[INFO]     [creator]     Restoring metadata for "paketo-buildpacks/ca-certificates:helper" from app image
[INFO]     [creator]     Restoring metadata for "paketo-buildpacks/bellsoft-liberica:jdk" from app image
[INFO]     [creator]     Restoring metadata for "paketo-buildpacks/bellsoft-liberica:helper" from app image
[INFO]     [creator]     Restoring metadata for "paketo-buildpacks/bellsoft-liberica:java-security-properties" from app image
[INFO]     [creator]     Restoring metadata for "paketo-buildpacks/syft:syft" from cache
[INFO]     [creator]     Restoring metadata for "paketo-buildpacks/spring-boot:helper" from app image
[INFO]     [creator]     Restoring metadata for "paketo-buildpacks/spring-boot:spring-cloud-bindings" from app image
[INFO]     [creator]     Restoring metadata for "paketo-buildpacks/spring-boot:web-application-type" from app image
[INFO]     [creator]     ===> RESTORING
[INFO]     [creator]     Restoring data for "paketo-buildpacks/bellsoft-liberica:jdk" from cache
[INFO]     [creator]     Restoring data for "paketo-buildpacks/syft:syft" from cache
[INFO]     [creator]     ===> BUILDING
[INFO]     [creator]
[INFO]     [creator]     Paketo CA Certificates Buildpack 3.0.1
[INFO]     [creator]       https://github.com/paketo-buildpacks/ca-certificates
[INFO]     [creator]       Launch Helper: Reusing cached layer
[INFO]     [creator]
[INFO]     [creator]     Paketo BellSoft Liberica Buildpack 9.0.1
[INFO]     [creator]       https://github.com/paketo-buildpacks/bellsoft-liberica
[INFO]     [creator]       Build Configuration:
[INFO]     [creator]         $BP_JVM_TYPE                 JDK                  the JVM type - JDK or JRE
[INFO]     [creator]         $BP_JVM_VERSION              11.*                 the Java version
[INFO]     [creator]       Launch Configuration:
[INFO]     [creator]         $BPL_DEBUG_ENABLED           true                 enables Java remote debugging support
[INFO]     [creator]         $BPL_DEBUG_PORT              8000                 configure the remote debugging port
[INFO]     [creator]         $BPL_DEBUG_SUSPEND           false                configure whether to suspend execution until a debugger has attached
[INFO]     [creator]         $BPL_HEAP_DUMP_PATH          /tmp/heapdump.hprof  write heap dumps on error to this path
[INFO]     [creator]         $BPL_JAVA_NMT_ENABLED        true                 enables Java Native Memory Tracking (NMT)
[INFO]     [creator]         $BPL_JAVA_NMT_LEVEL          summary              configure level of NMT, summary or detail
[INFO]     [creator]         $BPL_JFR_ARGS                                     configure custom Java Flight Recording (JFR) arguments
[INFO]     [creator]         $BPL_JFR_ENABLED             false                enables Java Flight Recording (JFR)
[INFO]     [creator]         $BPL_JMX_ENABLED             false                enables Java Management Extensions (JMX)
[INFO]     [creator]         $BPL_JMX_PORT                5000                 configure the JMX port
[INFO]     [creator]         $BPL_JVM_HEAD_ROOM           0                    the headroom in memory calculation
[INFO]     [creator]         $BPL_JVM_LOADED_CLASS_COUNT  35% of classes       the number of loaded classes in memory calculation
[INFO]     [creator]         $BPL_JVM_THREAD_COUNT        250                  the number of threads in memory calculation
[INFO]     [creator]         $JAVA_TOOL_OPTIONS                                the JVM launch flags
[INFO]     [creator]       A JDK was specifically requested by the user, however a JRE is available. Using a JDK at runtime has security implications.
[INFO]     [creator]       BellSoft Liberica JDK 11.0.13: Reusing cached layer
[INFO]     [creator]       Launch Helper: Reusing cached layer
[INFO]     [creator]       Java Security Properties: Reusing cached layer
[INFO]     [creator]
[INFO]     [creator]     Paketo Syft Buildpack 1.0.1
[INFO]     [creator]       https://github.com/paketo-buildpacks/syft
[INFO]     [creator]
[INFO]     [creator]     Paketo Executable JAR Buildpack 6.0.1
[INFO]     [creator]       https://github.com/paketo-buildpacks/executable-jar
[INFO]     [creator]       Class Path: Contributing to layer
[INFO]     [creator]         Writing env/CLASSPATH.delim
[INFO]     [creator]         Writing env/CLASSPATH.prepend
[INFO]     [creator]       Process types:
[INFO]     [creator]         executable-jar: java org.springframework.boot.loader.WarLauncher (direct)
[INFO]     [creator]         task:           java org.springframework.boot.loader.WarLauncher (direct)
[INFO]     [creator]         web:            java org.springframework.boot.loader.WarLauncher (direct)
[INFO]     [creator]
[INFO]     [creator]     Paketo Spring Boot Buildpack 5.1.0
[INFO]     [creator]       https://github.com/paketo-buildpacks/spring-boot
[INFO]     [creator]       Creating slices from layers index
[INFO]     [creator]         dependencies
[INFO]     [creator]         spring-boot-loader
[INFO]     [creator]         snapshot-dependencies
[INFO]     [creator]         application
[INFO]     [creator]       Launch Helper: Reusing cached layer
[INFO]     [creator]       Spring Cloud Bindings 1.8.0: Reusing cached layer
[INFO]     [creator]       Web Application Type: Contributing to layer
[INFO]     [creator]         Non-web application detected
[INFO]     [creator]         Writing env.launch/BPL_JVM_THREAD_COUNT.default
[INFO]     [creator]       4 application slices
[INFO]     [creator]       Image labels:
[INFO]     [creator]         org.springframework.boot.version
[INFO]     [creator]     ===> EXPORTING
[INFO]     [creator]     Reusing layer 'paketo-buildpacks/ca-certificates:helper'
[INFO]     [creator]     Reusing layer 'paketo-buildpacks/bellsoft-liberica:helper'
[INFO]     [creator]     Reusing layer 'paketo-buildpacks/bellsoft-liberica:java-security-properties'
[INFO]     [creator]     Reusing layer 'paketo-buildpacks/bellsoft-liberica:jdk'
[INFO]     [creator]     Reusing layer 'paketo-buildpacks/executable-jar:classpath'
[INFO]     [creator]     Reusing layer 'paketo-buildpacks/spring-boot:helper'
[INFO]     [creator]     Reusing layer 'paketo-buildpacks/spring-boot:spring-cloud-bindings'
[INFO]     [creator]     Reusing layer 'paketo-buildpacks/spring-boot:web-application-type'
[INFO]     [creator]     Reusing 4/5 app layer(s)
[INFO]     [creator]     Adding 1/5 app layer(s)
[INFO]     [creator]     Reusing layer 'launcher'
[INFO]     [creator]     Reusing layer 'config'
[INFO]     [creator]     Reusing layer 'process-types'
[INFO]     [creator]     Adding label 'io.buildpacks.lifecycle.metadata'
[INFO]     [creator]     Adding label 'io.buildpacks.build.metadata'
[INFO]     [creator]     Adding label 'io.buildpacks.project.metadata'
[INFO]     [creator]     Adding label 'org.springframework.boot.version'
[INFO]     [creator]     Setting default process type 'web'
[INFO]     [creator]     Saving docker.io/library/foconis-zak-war:1.43.0-RC5-SNAPSHOT...
[INFO]     [creator]     *** Images (795c8545a3bb):
[INFO]     [creator]           docker.io/library/foconis-zak-war:1.43.0-RC5-SNAPSHOT
[INFO]     [creator]     Reusing cache layer 'paketo-buildpacks/bellsoft-liberica:jdk'
[INFO]     [creator]     Reusing cache layer 'paketo-buildpacks/syft:syft'
[INFO]
[INFO] Successfully built image 'docker.io/library/foconis-zak-war:1.43.0-RC5-SNAPSHOT'
```

All of that was tested in Debian 11.1 running in WSL2.

## Checklist

* [x] I have included log output.
* [x] The log output includes an error message.
* [ ] I have included steps for reproduction.

**Comment by dmikusa-pivotal** [comment]
OK, so you're correct. The base images that Paketo ships do not have that library. 

The general thought process is that these are headless containers, so AWT is probably not something that would be necessary. AWT is largely used with Java Swing and desktop applications (side note: we don't ship JavaFX support either). Not shipping these extra dependencies helps to keep image sizes as low as possible.

That gives you a couple of options:

1. You can add the missing libraries. There's a [StackOverflow Post with instructions here](https://stackoverflow.com/a/69466535/1585136). I would probably take a look at option #4, using apt buildpack. I believe that should work, as it's setting `LD_LIBRARY_PATH`. If the app still has problems loading the native library after you get it installed with apt buildpack, then you may need to set the `-Djava.library.path` system property to include the path to which apt buildpack installs the dependencies. 

2. I'm not familiar with JavaMelody, but you could take a look and see if there's a way you can make it disable whatever part of the codebase that is requiring Java AWT. Ultimately, this is a cleaner option as you don't have to install any of that into your container and load it all into memory. If there is a legitimate reason it needs AWT, for functionality that you cannot disable, then you'll have to go with the previous option and install the dependencies.

**Comment by focdanisch** [comment]
Hi,

thank you for your reply. JavaMelody is not trying to draw a GUI, it just uses these awt classes internally. I also looked through the call trace, I do not see any option to turn off that behaviour.

The whole purpose of using buildpacks is to avoid writing a Dockerfile. The apt buildpack is experimental and not production ready. Apart from that, a separate file has to be maintained with the package list. It is also unclear if the whole "apt-without-root"-approch leads to a working image. In that case, it is much simpler for us to go down the Dockerfile route, along with the flexibility it provides.

Best regards,
Manuel

**Comment by dmikusa-pivotal** [comment]
>The apt buildpack is experimental and not production ready.

Are you looking at the right buildpack?  I don't believe that https://github.com/fagiani/apt-buildpack is experimental, and it gets a pretty good amount of use.

>It is also unclear if the whole "apt-without-root"-approch leads to a working image.

Did you try it? I'd say there's probably a 90-95% chance it'll work. When it doesn't work, it's because the program you're running cannot locate a shared library, due to it being in a non-standard location. I don't think that'll happen, but if it does for some reason it's very easy to tell the JVM where to find things, using `-Djava.library.path`.
